#!/bin/sh
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_pim_z350_p2.5_theta8.0_1e6.root",true,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_pim_z350_p7.5_theta14.5_1e6.root",true,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_pim_1e6.root",true,true,true)'

# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_km_z350_p2.5_theta8.0_1e5.root",false,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_km_z350_p7.5_theta14.5_1e5.root",false,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_km_1e5.root",false,true,true)'

# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/new/solid_SIDIS_He3_hgc_moved_pim_1e5.root",true,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/new/solid_SIDIS_He3_hgc_moved_km_1e5.root",false,true,true)'

# root  'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_pim_z350_p2.5_theta8.0_1e5.root",true,false,false)'

# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_pim_z350_p2.5_theta8.0_1e5.root",true,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_pim_z350_p7.5_theta14.5_1e5.root",true,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_pim_1e5.root",true,true,true)'

# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_km_z350_p2.5_theta8.0_1e5.root",false,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_km_z350_p7.5_theta14.5_1e5.root",false,true,true)'
# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_km_1e5.root",false,true,true)'

# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi45-145_yesblock_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p2.5_theta14.8_phi45-145_yesblock_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p7.5_theta8.0_phi45-145_yesblock_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p7.5_theta14.8_phi45-145_yesblock_1e3.root","hgc",false,false,0)'
 
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p7.5_theta8.0_phi45-145_noblock_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p7.5_theta8.0_phi45-145_yesblock_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p7.5_theta14.8_phi45-145_noblock_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p7.5_theta14.8_phi45-145_yesblock_1e3.root","hgc",false,false,0)'

# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_BeamOnTarget_5e10_filter.root","lgc")'
# 
# root  'analysis.C+("/test_lgc/out.root_5ns","lgc",false,false,true,0,"./")'
# 
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p3.0_theta12.0_1e6.root","lgcec",false,false,true,0,"solid_SIDIS_He3_full_lgcec")'
# 
# root  -b -q -l  'analysis_aiml_bg.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_BeamOnTarget_5e10_filter.root","lgcec")'
# 
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p3.0_theta12.0_1e6.root","lgcec",true,true,true,0,"solid_SIDIS_He3_full_lgcec/backgroundno_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p3.0_theta12.0_1e6.root","lgcec",true,true,true,1,"solid_SIDIS_He3_full_lgcec/background3sector_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p3.0_theta12.0_1e6.root","lgcec",true,true,true,2,"solid_SIDIS_He3_full_lgcec/background3sectordouble_nodecaytrack")'
# 
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_pim_z350_p3.0_theta12.0_1e6.root","lgcec",false,true,true,0,"solid_SIDIS_He3_full_lgcec/backgroundno_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_pim_z350_p3.0_theta12.0_1e6.root","lgcec",false,true,true,1,"solid_SIDIS_He3_full_lgcec/background3sector_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_pim_z350_p3.0_theta12.0_1e6.root","lgcec",false,true,true,2,"solid_SIDIS_He3_full_lgcec/background3sectordouble_nodecaytrack")'
# 
# root  -b -q -l  'analysis_aiml_bg.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_BeamOnTarget_1e10_filter.root","lgcec")'
# 
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_ele_z10_p2.5_theta22_1e6.root","lgcec",true,true,true,0,"solid_PVDIS_LD2_full_lgcec/backgroundno_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_ele_z10_p2.5_theta22_1e6.root","lgcec",true,true,true,1,"solid_PVDIS_LD2_full_lgcec/background3sector_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_ele_z10_p2.5_theta22_1e6.root","lgcec",true,true,true,2,"solid_PVDIS_LD2_full_lgcec/background3sectordouble_nodecaytrack")'
# 
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_pim_z10_p2.5_theta22_1e6.root","lgcec",false,true,true,0,"solid_PVDIS_LD2_full_lgcec/backgroundno_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_pim_z10_p2.5_theta22_1e6.root","lgcec",false,true,true,1,"solid_PVDIS_LD2_full_lgcec/background3sector_nodecaytrack")'
# root -l 'analysis_aiml.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_pim_z10_p2.5_theta22_1e6.root","lgcec",false,true,true,2,"solid_PVDIS_LD2_full_lgcec/background3sectordouble_nodecaytrack")'

# root  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p2.5_theta8.0_1e6.root","lgc",false,false,true,0,"./")'

# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p2.5_theta8.0_1e6.root","lgc",true,true,true,0,"backgroundno_nodecaytrack")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_pim_z350_p2.5_theta8.0_1e6.root","lgc",false,true,true,0,"backgroundno_nodecaytrack")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p4.5_theta14.5_1e6.root","lgc",true,true,true,0,"backgroundno_nodecaytrack")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_pim_z350_p4.5_theta14.5_1e6.root","lgc",false,true,true,0,"backgroundno_nodecaytrack")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p3.0_theta12.0_1e6.root","lgc",true,true,true,0,"backgroundno_nodecaytrack")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_pim_z350_p3.0_theta12.0_1e6.root","lgc",false,true,true,0,"backgroundno_nodecaytrack")'

# void analysis(string input_filename,string cherenkov,bool Is_simsafe=false,bool Is_textfile=false, bool Is_decaycut=false, int factor_background=0,string the_dir=".")

# produce background file
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_BeamOnTarget_1e10_filter.root","lgc")'

# root  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_ele_z10_p2.5_theta22_1e6.root","lgc",false,false,true,0,"./")'

# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_ele_z10_p2.5_theta22_1e6.root","lgc",true,true,true,0,"solid_PVDIS_LD2_full_lgc/backgroundno_nodecaytrack_1sector")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_pim_z10_p2.5_theta22_1e6.root","lgc",false,true,true,0,"solid_PVDIS_LD2_full_lgc/backgroundno_nodecaytrack_1sector")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_ele_z10_p4.5_theta34_1e6.root","lgc",true,true,true,0,"solid_PVDIS_LD2_full_lgc/backgroundno_nodecaytrack_1sector")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LD2_moved_full_pim_z10_p4.5_theta34_1e6.root","lgc",false,true,true,0,"solid_PVDIS_LD2_full_lgc/backgroundno_nodecaytrack_1sector")'


# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_BeamOnTarget_5e10_filter.root","lgc")'
# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_BeamOnTarget_5e10_filter.root","hgc")'

# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/PVDIS_JLAB_VERSION_2.5/pass3/solid_PVDIS_LH2_moved_full_BeamOnTarget_1e10_filter.root","lgc")'

# root  -b -q -l  'analysis.C+("/cache/halla/solid/sim/solid_gemc/JPsi_JLAB_VERSION_2.5/pass3/solid_JPsi_LH2_moved_full_BeamOnTarget_5e9_filter.root","lgc")'




# root  -b -q -l  'analysis.C+("/volatile/halla/solid/sim/solid_gemc/SIDIS_He3_JLAB_VERSION_2.5/pass3/solid_SIDIS_He3_moved_full_ele_z350_p2.5_theta8.0_1e6_new.root","lgc",false,false,false)'


# root -b -q -l 'analysis_hgc.C+("output/hgc_moved/solid_SIDIS_He3_hgc_moved_km_z350_p2.5_theta8.0_phi0_1e4.root",true,true)'

# root 'analysis_hgc.C+("output/cherenkov/cherenkov_CO2_e_p5.0_1e3.root",false,true,true)'

# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p2.5_theta7.5_phi0_blockoff_fieldoff_1e3.root")'
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p3.0_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p3.5_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p4.0_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p4.5_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p5.0_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p5.5_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p6.0_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p6.5_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p7.0_theta7.5_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p7.5_theta7.5_phi0_blockoff_fieldoff_1e3.root")'
# 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p2.5_theta8.0_phi0_blockoff_fieldoff_1e3.root")'
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p3.0_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p3.5_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p4.0_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p4.5_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p5.0_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p5.5_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p6.0_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p6.5_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p7.0_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p7.5_theta8.0_phi0_blockoff_fieldoff_1e3.root")' 
# 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p2.5_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p3.0_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p3.5_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p4.0_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p4.5_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p5.0_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p5.5_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p6.0_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p6.5_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p7.0_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 
# root -b -q -l 'analysis.C+("output/solid_SIDIS_He3_hgc_moved_pim_z0_p7.5_theta14.8_phi0_blockoff_fieldoff_1e3.root")' 

# root  'analysis_hgc.C+("output/hgc_moved/pass1/solid_SIDIS_He3_moved_full_pim_z350_p2.5_theta8.0_1e5_new.root",true,false,true)'

# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi57-63_yesblock_1e4.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p2.5_theta14.8_phi67-73_yesblock_1e4.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi57-63_yesblockmirror1_1e4.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testblock/hgc_SIDIS_He3_pim_z350_p2.5_theta14.8_phi67-73_yesblockmirror1_1e4.root","hgc",false,false,0)'

# root  -b -q -l  'analysis.C+("output/testmirror/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi360_nochange_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testmirror/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi360_row-5cm_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testmirror/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi360_row-10cm_1e3.root","hgc",false,false,0)'
# root  -b -q -l  'analysis.C+("output/testmirror/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi360_row-15cm_1e3.root","hgc",false,false,0)'

root   'analysis.C+("output/testmirror/hgc_SIDIS_He3_pim_z350_p2.5_theta8.0_phi360_1e3.root","hgc",false,false)'
